version: "3.7"
services:
  data_collector:
    build:
      context: .  # O diretório atual onde o Dockerfile está localizado
    command: python /app/venv/src/data_collector_agua_v2.py 
    container_name: data_collector
    volumes:
      - .:/app  # Monta o diretório local dentro do contêiner em /app
    networks:
      - monitoring
    depends_on:
      - prometheus 

  data_processor:
    build:
      context: .  # O diretório atual onde o Dockerfile está localizado
    command: python /app/venv/src/data_processor_agua_v2.py 
    container_name: data_processor
    volumes:
      - .:/app  # Monta o diretório local dentro do contêiner em /app
    networks:
      - monitoring
    depends_on:
      - data_collector  
      - prometheus 

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    restart: unless-stopped  

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge  # Rede compartilhada entre todos os serviços
